# Generated by Django 3.1.7 on 2021-05-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210429_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boost',
            old_name='cycle',
            new_name='mainCycle',
        ),
    ]
