# Generated by Django 3.1.7 on 2021-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210509_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
