# Generated by Django 3.1.7 on 2021-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_maincycle_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='boost_id',
            field=models.IntegerField(default=0),
        ),
    ]
