# Generated by Django 3.1.7 on 2021-05-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_boost_boost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='level_cost',
            field=models.IntegerField(default=5),
        ),
    ]
